apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  containers:
    - name: consumer
      image: 149095730232.dkr.ecr.eu-central-1.amazonaws.com/jenkins-x:jenkins-x-nodejs-consumer-v2
      ports:
        - name: consumer-port
          containerPort: 3001
